### ISSUE TITLE
When building docker image ,come on a error

### ISSUE THREAD

**Issue by yonglpy** [cancerit/ascatNgs#102]
when using Dockerfile to build image,the following message appears:
Step 51/81 : COPY build/Rprofile $OPT/config/Rprofile
COPY failed: stat /var/lib/docker/tmp/docker-builder005224817/build/Rprofile: no such file or directory
Has anyone encountered such a problem when building a mirror?

**Comment by keiranmraine** [comment]
Can you confirm which tag or commit of the repository was in use?  Also are you sure the local file system wasn't full?

FYI you don't need to build the image it can be downloaded from Quay.io by tag: https://quay.io/repository/wtsicgp/ascatngs

e.g.

```
docker pull quay.io/wtsicgp/ascatngs:4.5.0
```

or for singularity:

```
singularity pull docker://quay.io/wtsicgp/ascatngs:4.5.0
```

**Comment by sotaro-kanematsu** [comment]
Hi keiranmraine 
I am going to use ascatNGS to uncover allele-specific somatic copy number alternations in clinical samples (tumor-normal pair).
I pull the docker images as you explained as above, however, I don't know how to handle the docker images to get results because I am only a beginner.  
Could you teach me the example command using docker images to get the list of allele-specific somatic copy number alternations?
In addition to that, I would like to know how to construct SnpGcCorrections.tsv file under the docker enviornment.

**Comment by keiranmraine** [comment]
@sotaro-kanematsu please see: https://github.com/cancerit/ascatNgs/wiki/Basic-usage#docker
