### ISSUE TITLE
setup.sh fails to find pre-req PERL5LIB dirs

### ISSUE THREAD

**Issue by ink1** [cancerit/ascatNgs#42]
Hi,
Is the supported mechanism for telling where the dependencies are to supply CGP_PERLLIBS?
Then the installation instructions should say so. At the end of installation of each dependency,  PERL5LIB is set/updated but the first thing the setup script does is to reset it. The following seems to work though:
export CGP_PERLLIBS=$PERL5LIB
./setup.sh /some/ascatngs/2.0.1

**Comment by keiranmraine** [comment]
I've updated the docs for the next release, however please see below for an explanation why we don't blindly use `PERL5LIB`.

The code was originally designed to be build in a contained 'pipeline' way expecting all code to be installed to the same destination, e.g. all setup.sh executed as:

````
./setup.sh /opt/wtsi-cgp_20160426
````

We have added `CGP_PERLLIB` latterly to projects to allow users who want to install each element to a different path (i.e. versioned by release).  It does not use `PERL5LIB` as the intention is to ensure that no dependancies are fulfilled by paths outside of your control.  If you want to use `PERL5LIB` the approach you have is correct.

There is nothing worse that finding a system perl library has been updated which creates an undesired side-effect which is why this doesn't use your `PERL5LIB` unless it is re-exported as `CGP_PERLLIB`.  For example if you did an install with your PERL5LIB you may have libraries available, but when another user installs they may no-longer be fulfilled.

Please be aware that due to the interdependency of tools (especially in latter releases) we really do recommend a clean stack is built.
