### ISSUE TITLE
quay.io version does not match program version

### ISSUE THREAD

**Issue by GodloveD** [cancerit/ascatNgs#96]
Hi there.  I'm trying to use the 4.3.4 tag from [quay.io](https://quay.io/repository/wtsicgp/ascatngs?tab=tags).  The container is tagged as 4.3.4.  But `ascat.pl --version` is reporting 4.3.3.  Was the wrong version installed in the container?  Was the 4.3.4 version not updated to show it's current version?  Or is the container version expected to be different from the version installed in the container?

**Comment by rulixxx** [comment]
Hi David,

Good spot, that was an error on my part because I didn't cut the release correctly for version 4.3.4 . I just forgot to update the version number in the perl module. All the code in quay.io is up to date otherwise

Will fix the tag 4.3.4 to fix this error

Regards

Raul


________________________________
